mkdir ../tmp
mkdir ../tmp/error
mkdir ../tmp/qqdata
mkdir ../tmp/qqdatabs
mkdir ../tmp/qqdataxjl
mkdir ../tmp/success
mkdir ../tmp/tencent
mkdir ../tmp/tencent_basic
mkdir ../tmp/tencent_analysis
mkdir ../tmp/tencent_combine
mkdir ../tmp/tencent_mj_data